### ISSUE TITLE
FATAL error if `nc` is not installed

### ISSUE THREAD

**Issue by jpcarey** [jpcarey/ece-support-diagnostics#4]
The zookeeper mntr command currently sends `echo mntr|nc ip port`. If `nc` is not on the $PATH, this causes a FATAL error.

```
2019-09-19T14:56:57.157Z        INFO    [zookeeper]     Collecting zookeeper mntr
2019-09-19T14:56:57.158Z        FATAL   [zookeeper]     It didn't work:
exec: "nc": executable file not found in $PATH
```

https://github.com/jpcarey/ece-support-diagnostics/blob/master/collectors/zookeeper/zookeeper-collector.go#L48-L50

Need to handle this error, but ultimately should rewrite to remove the need for `nc` to send a simple string over TCP.

thanks for reporting @inqueue

**Comment by jakommo** [comment]
The zookeeper container has `nc` installed, so we could run the command inside the container.
i.e. `docker exec frc-zookeeper-servers-zookeeper sh -c '/usr/bin/echo mntr | /usr/bin/nc localhost 2191'`

**Comment by jpcarey** [comment]
fixed with https://github.com/jpcarey/ece-support-diagnostics/commit/9ab5602233e3dccf22be340099471d0870dbc4b3 commit. New release coming soon.
